# Generated by Django 4.2.7 on 2024-01-04 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Matching_dict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser', models.CharField(max_length=30)),
                ('matcher', models.CharField(max_length=30)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.customers')),
            ],
        ),
    ]
