# Generated by Django 4.2.7 on 2024-01-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_customers_matching_dict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matching_dict',
            name='customer_name',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Matching_dict',
        ),
    ]
