# Generated by Django 4.2.7 on 2024-01-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_alter_matching_dict_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching_dict',
            name='customer_name',
            field=models.CharField(max_length=30),
        ),
    ]
