# Generated by Django 4.2.7 on 2024-01-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_alter_matching_dict_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='sku_bl',
            field=models.BooleanField(null=True),
        ),
    ]
