# Generated by Django 4.2.7 on 2024-01-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_original_salesimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_salesimport',
            name='PO_Number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Retailers_PO',
            field=models.BigIntegerField(null=True),
        ),
    ]
