# Generated by Django 4.2.7 on 2024-01-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_remove_original_salesimport_po_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='original_salesimport',
            name='PO_Date',
            field=models.DateField(null=True),
        ),
    ]
