# Generated by Django 4.2.7 on 2024-01-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_original_salesimport_po_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Original_SalesImport',
        ),
    ]
