# Generated by Django 4.2.7 on 2024-01-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0014_original_salesimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_salesimport',
            name='Additional_Vendor_Part',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Agreement_Number',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='AllowCharge',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='AllowCharge_Amt',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='AllowCharge_Desc',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='AllowCharge_Qty',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='AllowCharge_Rate',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='AllowCharge_Service',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='AllowCharge_Type',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Bill_To_Additional_Name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Bill_To_Additional_Name_2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Bill_To_Address_1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Bill_To_Address_2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Bill_To_City',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Bill_To_Contact',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Bill_To_Country',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Bill_To_Name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Bill_To_State',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Buyer_Additional_Name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Buyer_Additional_Name_2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Buyer_Part_Number',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Buying_Party_Address_1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Buying_Party_Address_2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Buying_Party_City',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Buying_Party_Contact',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Buying_Party_Country',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Buying_Party_Location',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Buying_Party_Name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Buying_Party_State',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Carrier',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Carrier_Details',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Carrier_Details_Special_Handling',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Carrier_Service_Level',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Color',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Contact_Email',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Contact_Fax',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Contact_Phone',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Contract_Number',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Currency',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Cust_Acct',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Customer_Order',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Dept',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Dist',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Division',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Entire_Shipment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Expiration_Date',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Frt_Terms',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='GTIN',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Letter_of_Credit',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Mark_for_Address_1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Mark_for_Address_2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Mark_for_City',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Mark_for_Country',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Mark_for_Name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Mark_for_State',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Must_Arrive_By',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='National_Drug_Code',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Notes_Comments',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Other_Info',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='PO_Total_UOM',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='PO_Type',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='PO_purpose',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Pack_Size',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Payment_Terms',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Payment_Terms_Desc',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Payment_Terms_Disc_Amt',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Payment_Terms_Disc_Days_Due',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Payment_Terms_Disc_Due_Date',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Payment_Terms_Net_Days',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Payment_Terms_Net_Due_Date',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Promo',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Required_By_Date',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Restrictions_Conditions',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Scheduled_Qty_UOM',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Scheduled_Quantity',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Ship_Status',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Ship_To_Additional_Name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Ship_To_Additional_Name_2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Ship_To_Address_1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Ship_To_Address_2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Ship_To_City',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Ship_To_Contact',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Ship_To_Country',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Ship_To_Name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Ship_To_State',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Shipping_Container_Code',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Shipping_account_number',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Ticket_Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Ultimate_Location',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='processhistory',
            name='input',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='processhistory',
            name='output',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
