# Generated by Django 4.2.7 on 2024-01-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0015_alter_original_salesimport_additional_vendor_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_salesimport',
            name='Bill_To_Zip',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Buying_Party_Zip',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Mark_for_Postal',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Number_of_Inner_Packs',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Number_of_Pcs_per_Inner_Pack',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='PO_Line',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Qty_Ordered',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Qty_per_Store',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Ship_To_Location',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Ship_to_Zip',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Vendor',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Vendor_Style',
            field=models.BigIntegerField(null=True),
        ),
    ]
