# Generated by Django 4.2.7 on 2024-01-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0016_alter_original_salesimport_bill_to_zip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_salesimport',
            name='Pack_Size_UOM',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Record_Type',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Store',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
