# Generated by Django 4.2.7 on 2024-01-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0022_alter_original_salesimport_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_salesimport',
            name='created',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
