# Generated by Django 4.2.7 on 2024-01-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0027_delete_oms_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='OMS_Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Status', models.CharField(max_length=100, null=True)),
                ('Currency', models.CharField(max_length=25, null=True)),
                ('PaymentTerm', models.CharField(max_length=100, null=True)),
                ('TaxRule', models.CharField(max_length=100, null=True)),
                ('AccountReceivable', models.IntegerField(null=True)),
                ('SaleAccount', models.IntegerField(null=True)),
                ('PriceTier', models.CharField(max_length=100, null=True)),
                ('Discount', models.IntegerField(null=True)),
                ('CreditLimit', models.IntegerField(null=True)),
                ('Carrier', models.CharField(max_length=100, null=True)),
                ('SalesRepresentative', models.CharField(max_length=100, null=True)),
                ('Location', models.CharField(max_length=100, null=True)),
                ('TaxNumber', models.CharField(max_length=100, null=True)),
                ('Tags', models.CharField(max_length=1000, null=True)),
                ('AttributeSet', models.CharField(max_length=1000, null=True)),
                ('AdditionalAttribute1', models.CharField(max_length=1000, null=True)),
                ('AdditionalAttribute2', models.CharField(max_length=1000, null=True)),
                ('AdditionalAttribute3', models.CharField(max_length=1000, null=True)),
                ('AdditionalAttribute4', models.CharField(max_length=1000, null=True)),
                ('AdditionalAttribute5', models.CharField(max_length=1000, null=True)),
                ('AdditionalAttribute6', models.CharField(max_length=1000, null=True)),
                ('AdditionalAttribute7', models.CharField(max_length=1000, null=True)),
                ('AdditionalAttribute8', models.CharField(max_length=1000, null=True)),
                ('AdditionalAttribute9', models.CharField(max_length=1000, null=True)),
                ('AdditionalAttribute10', models.CharField(max_length=1000, null=True)),
                ('Comments', models.CharField(max_length=1000, null=True)),
                ('ContactName', models.CharField(max_length=100, null=True)),
                ('JobTitle', models.CharField(max_length=1000, null=True)),
                ('Phone', models.CharField(max_length=100, null=True)),
                ('MobilePhone', models.CharField(max_length=100, null=True)),
                ('Fax', models.CharField(max_length=100, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('Website', models.CharField(max_length=100, null=True)),
                ('ContactComment', models.CharField(max_length=100, null=True)),
                ('ContactDefault', models.BooleanField(null=True)),
                ('ContactIncludeInEmail', models.BooleanField(null=True)),
                ('MarketingConsent', models.CharField(max_length=100, null=True)),
                ('IsAccountingDimensionEnabled', models.BooleanField(null=True)),
                ('DimensionAttribute1', models.CharField(max_length=1000, null=True)),
                ('DimensionAttribute2', models.CharField(max_length=1000, null=True)),
                ('DimensionAttribute3', models.CharField(max_length=1000, null=True)),
                ('DimensionAttribute4', models.CharField(max_length=1000, null=True)),
                ('DimensionAttribute5', models.CharField(max_length=1000, null=True)),
                ('DimensionAttribute6', models.CharField(max_length=1000, null=True)),
                ('DimensionAttribute7', models.CharField(max_length=1000, null=True)),
                ('DimensionAttribute8', models.CharField(max_length=1000, null=True)),
                ('DimensionAttribute9', models.CharField(max_length=1000, null=True)),
                ('DimensionAttribute10', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
