# Generated by Django 4.2.7 on 2024-01-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0030_oms_customers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OMS_AdditionalUOM',
        ),
    ]
