# Generated by Django 4.2.7 on 2024-01-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0034_oms_inventory_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OMS_Inventory_List',
        ),
    ]
