# Generated by Django 4.2.7 on 2024-01-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0039_oms_inventory_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oms_additionaluom',
            name='Action',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_additionaluom',
            name='AdditionalUnitsOfMeasureName',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_additionaluom',
            name='AdditionalUnitsOfMeasureProductName',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_additionaluom',
            name='AdditionalUnitsOfMeasureSKU',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_additionaluom',
            name='BaseProductName',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_additionaluom',
            name='BaseSKU',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_additionaluom',
            name='BaseUnitsOfMeasure',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_customers',
            name='Carrier',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_customers',
            name='ContactComment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_customers',
            name='ContactName',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_customers',
            name='Currency',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_customers',
            name='Email',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_customers',
            name='Fax',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_customers',
            name='Location',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_customers',
            name='MarketingConsent',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_customers',
            name='MobilePhone',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_customers',
            name='Name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_customers',
            name='PaymentTerm',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_customers',
            name='Phone',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_customers',
            name='PriceTier',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_customers',
            name='SalesRepresentative',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_customers',
            name='Status',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_customers',
            name='TaxNumber',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_customers',
            name='TaxRule',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_customers',
            name='Website',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='AssemblyBOM',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='AutoAssemble',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='AutoDisassemble',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='Brand',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='Category',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='CostingMethod',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='CountryOfOrigin',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='DefaultLocation',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='DefaultUnitOfMeasure',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='DimensionUnits',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='DropShip',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='DropShipSupplier',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='FixedAssetType',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='LastSuppliedBy',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='MakeToOrderBom',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='Name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='ProductCode',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='ProductFamilyOption1Name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='ProductionBOM',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='SupplierProductCode',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='SupplierProductName',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='Type',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='WeightUnits',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_locations',
            name='Location',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_payment_term',
            name='Name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_uom',
            name='Name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Size',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Unit_of_Measure',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='created',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
