# Generated by Django 4.2.7 on 2024-01-05 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0040_alter_oms_additionaluom_action_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OMS_Inventory_List',
        ),
    ]
