# Generated by Django 4.2.7 on 2024-01-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0042_oms_inventory_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input_paths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200, null=True)),
                ('created', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
