# Generated by Django 4.2.7 on 2024-01-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0043_input_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='input_paths',
            name='file_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
