# Generated by Django 4.2.7 on 2024-01-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0044_input_paths_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_salesimport',
            name='PO_Number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Release_Number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
