# Generated by Django 4.2.7 on 2024-01-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0045_alter_original_salesimport_po_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_salesimport',
            name='Retailers_PO',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
