# Generated by Django 4.2.7 on 2024-01-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0046_alter_original_salesimport_retailers_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_salesimport',
            name='Ship_To_Location',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
