# Generated by Django 4.2.7 on 2024-01-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0047_alter_original_salesimport_ship_to_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_salesimport',
            name='Vendor',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
