# Generated by Django 4.2.7 on 2024-01-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0049_alter_original_salesimport_vendor_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_salesimport',
            name='Ship_to_Zip',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
