# Generated by Django 4.2.7 on 2024-01-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0050_alter_original_salesimport_ship_to_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_salesimport',
            name='UPC_EAN',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
