# Generated by Django 4.2.7 on 2024-01-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0051_alter_original_salesimport_upc_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_salesimport',
            name='Buyers_Catalog_or_Stock_Keeping',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
