# Generated by Django 4.2.7 on 2024-01-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0052_alter_original_salesimport_buyers_catalog_or_stock_keeping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_salesimport',
            name='Bill_To_Zip',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
