# Generated by Django 4.2.7 on 2024-01-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0053_alter_original_salesimport_bill_to_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesImport_fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_names', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
