# Generated by Django 4.2.7 on 2024-01-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0054_salesimport_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='Barcode',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
