# Generated by Django 4.2.7 on 2024-01-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0055_alter_oms_inventory_list_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocustomer_fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Oinventory_fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Olocation_fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
            ],
        ),
    ]
