# Generated by Django 4.2.7 on 2024-03-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0056_ocustomer_fields_oinventory_fields_olocation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_salesimport',
            name='Buying_Party_Zip',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
