# Generated by Django 4.2.7 on 2024-03-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0057_alter_original_salesimport_buying_party_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_salesimport',
            name='PO_Line',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Qty_Ordered',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
