# Generated by Django 4.2.7 on 2024-03-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0058_alter_original_salesimport_po_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_salesimport',
            name='Retail_Price',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='original_salesimport',
            name='Unit_Price',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
