# Generated by Django 4.2.7 on 2024-08-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0059_alter_original_salesimport_retail_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oms_customers',
            name='CreditLimit',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_customers',
            name='Discount',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
