# Generated by Django 4.2.7 on 2024-08-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0060_alter_oms_customers_creditlimit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oms_customers',
            name='CreditLimit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='oms_customers',
            name='Discount',
            field=models.IntegerField(null=True),
        ),
    ]
