# Generated by Django 4.2.7 on 2024-08-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0061_alter_oms_customers_creditlimit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='AlwaysShowQuantity',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='AverageCost',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='CartonHeight',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='CartonInnerQuantity',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='CartonLength',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='CartonQuantity',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='CartonVolume',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='CartonWidth',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='Height',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='Length',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='PriceTier1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='PriceTier10',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='PriceTier2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='PriceTier3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='PriceTier4',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='PriceTier5',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='PriceTier6',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='PriceTier7',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='PriceTier8',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='PriceTier9',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='SupplierFixedPrice',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='Weight',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oms_inventory_list',
            name='Width',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
